# Generated by Django 6.0.4 on 2026-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', '식비'), ('transport', '교통비'), ('fixed', '고정비용'), ('savings', '저축'), ('living', '생활비'), ('culture', '문화생활'), ('other', '기타')], max_length=20),
        ),
    ]
